name: Access macOS Runner via ngrok

on:
  workflow_dispatch:

jobs:
  open-tunnel:
    runs-on: macos-latest
    steps:
      - name: Install ngrok
        run: brew install ngrok/ngrok/ngrok

      - name: Authenticate ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start SSH service
        run: |
          sudo systemsetup -setremotelogin on
          echo "root:password123" | sudo chpasswd

      - name: Start ngrok TCP tunnel (port 22)
        run: |
          nohup ngrok tcp 22 > ngrok.log &
          sleep 5
          grep -o 'tcp://[^ ]*' ngrok.log

      - name: Print connection info
        run: |
          echo "======================================"
          echo "Ngrok SSH Tunnel Info:"
          grep -o 'tcp://[^ ]*' ngrok.log
          echo "Use this command to connect:"
          echo "ssh root@<ngrok-host> -p <ngrok-port>"
          echo "Password: password123"
          echo "======================================"
