name: macOS SSH Access

on:
  workflow_dispatch:

jobs:
  ssh-access:
    runs-on: macos-latest
    steps:
      - name: Install ngrok
        run: |
          brew install --cask ngrok

      - name: Start SSH
        run: |
          echo "Password: github123"
          sudo dscl . -passwd /Users/runner github123
          sudo systemsetup -setremotelogin on
          sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

      - name: Start ngrok tunnel for SSH
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          ngrok config add-authtoken "$NGROK_AUTHTOKEN"
          ngrok tcp 22 > ngrok.log &
          sleep 5
          echo "================ NGROK TUNNEL INFO ================"
          cat ngrok.log | grep -Eo "tcp://[0-9a-zA-Z\.\-:]+"
          echo "===================================================="

      - name: Keep session alive
        run: sleep 1h
