name: macOS SSH Access (Stable)

on:
  workflow_dispatch:

jobs:
  ssh-access:
    runs-on: macos-latest

    steps:
      - name: Install ngrok
        run: brew install --cask ngrok

      - name: Create new SSH user
        run: |
          USERNAME=ghuser
          PASSWORD=github123

          # Buat user baru
          sudo sysadminctl -addUser $USERNAME -password $PASSWORD

          # Masukkan user ke grup admin
          sudo dscl . -append /Groups/admin GroupMembership $USERNAME

          # Aktifkan Remote Login (SSH)
          sudo systemsetup -setremotelogin on

          # Pastikan service SSH berjalan
          sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

          echo "✅ User '$USERNAME' dibuat dengan password '$PASSWORD'"
          echo "✅ SSH sudah aktif"
          
      - name: Start ngrok TCP tunnel (SSH)
        run: |
         brew install ngrok
         ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
         ngrok tcp 22 > ngrok.log &
         sleep 5
         curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep runner alive
        run: sleep 1h
