name: Android Runner
on:
  workflow_dispatch:
jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

  # Download & install the Android SDK.
    - uses: malinskiy/action-android/install-sdk@release/0.1.6

  # Set up platform tools like adb.
    - run: sdkmanager platform-tools

  # Start ADB (and verify that pathing is working correctly).
    - run: |
          sleep 500
          adb devices

  # Verify $ANDROID_HOME is properly set for later Gradle commands.
    - run: echo $ANDROID_HOME
