name: Run iOS Simulator & Appium on GitHub Actions

on: [workflow_dispatch]

jobs:
  ios-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install node
          npm install -g appium
          appium -v
          appium driver install xcuitest
          appium plugin install --source=npm appium-inspector-plugin

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 16 Pro"
          xcrun simctl list devices booted
      
      - name: Ambil UDID iPhone 16 Pro yang Booted
        run: |
          UDID=$(xcrun simctl list devices | grep "iPhone 16 Pro" | grep "(Booted)" | awk -F '[()]' '{print $2}')
          if [ -z "$UDID" ]; then
            echo "❌ Tidak menemukan UDID iPhone 16 Pro yang Booted!"
            exit 1
          fi
          echo "✅ UDID ditemukan: $UDID"
          echo "UDID=$UDID" >> $GITHUB_ENV

     # - name: Clone Appium Inspector Web
     #   run: |
     #     git clone https://github.com/aditiaangga/appium-inspector.git
     #     cd appium-inspector
     #     npm install

     #  - name: Start Appium Inspector Web
     #   run: |
     #     cd appium-inspector
     #     npm run dev:browser &

      - name: Start Appium Server
        run: |
          appium --use-plugins=inspector --allow-cors &

      - name: Install ngrok on macOS
        if: runner.os == 'macOS'
        run: |
          set -e
          echo "Installing ngrok on macOS..."
          brew install ngrok

      - name: Download ZIP File
        run: |
          curl -L -o ~/Downloads/sample-app.zip "https://github.com/cloudgrey-io/the-app/releases/download/v1.10.0/TheApp-v1.10.0.app.zip"

      - name: Extract ZIP
        run: |
          echo "Extract ZIP"
          unzip ~/Downloads/sample-app.zip -d ~/Downloads/extracted_app
          echo "Cek hasil extract"
          ls -R ~/Downloads/extracted_app  # Cek isi folder hasil ekstrak
          echo $HOME/Downloads/extracted_app/TheApp.app
      
      - name: Install App on iOS Simulator
        run: |
          xcrun simctl install "$UDID" ~/Downloads/extracted_app/TheApp.app
          xcrun simctl listapps booted
          # xcrun simctl listapps booted | grep saucelabs
          # xcrun simctl launch booted com.saucelabs.SwagLabsMobileApp

      
      - name: Expose Appium Server via ngrok
        run: |
          set -e
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok http --url=normal-hamster-typically.ngrok-free.app --host-header=rewrite 4723 > /dev/null 2>&1 & disown
          echo "Starting ngrok..."
      
      - name: Get ngrok Public URL
        run: |
          set -e
          while true; do
            NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
            if [[ "$NGROK_URL" == http* ]]; then
              echo "ngrok is ready: $NGROK_URL"
              echo "Appium Inspector Web can be accessed at: $NGROK_URL"
              break
            fi
            echo "Waiting for ngrok..."
            sleep 5
          done
          
      - name: Check Appium Server
        run: |
          ps aux | grep appium
          curl -v http://127.0.0.1:4723/wd/hub/status
          appium driver list --installed
          xcode-select --print-path
          which xcodebuild
          xcodebuild -version
      
      - name: Access to Ngrok
        run: |
          sleep 10000
