name: Run iOS Simulator & Appium on GitHub Actions

on: [workflow_dispatch]

jobs:
  ios-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install node
          npm install -g appium
          appium -v

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 16 Pro"
          xcrun simctl list devices booted

      - name: Clone Appium Inspector Web
        run: |
          git clone https://github.com/appium/appium-inspector.git
          cd appium-inspector
          npm install

      - name: Update Vite Config to Allow Ngrok
        run: |
          echo "export default { server: { host: '0.0.0.0', port: 5173, strictPort: true, allowedHosts: ['*'] } };" > appium-inspector/vite.config.mjs

      - name: Start Appium Inspector Web
        run: |
          cd appium-inspector
          npm run dev:browser &
          sleep 10

      - name: Expose Appium Inspector Web via ngrok
        run: |
          ngrok config add-authtoken 2szG7W6hTKx1SL37QX4ScuAo5IA_3PBBVuS2tPYJhoN9EqLoU
          ngrok http 5173 &
          sleep 10

      - name: Get ngrok Public URL
        run: |
          while true; do
           NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
           if [[ "$NGROK_URL" == http* ]]; then
            echo "ngrok is ready: $NGROK_URL"
            break
           fi
           echo "Waiting for ngrok..."
           sleep 5
          done
          echo "Appium Inspector Web can be accessed at: $NGROK_URL"
          sleep 100
