name: Run iOS Simulator & Appium on GitHub Actions

on: [workflow_dispatch]

jobs:
  ios-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install node
          npm install -g appium
          appium -v

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 16 Pro"
          xcrun simctl list devices booted

      - name: Start Appium Server
        run: |
          appium --log appium.log --allow-cors &
          sleep 10  # Tunggu Appium siap

      - name: Create Serveo Tunnel for Appium
        run: |
          ssh -o "StrictHostKeyChecking=no" -R 4723:localhost:4723 serveo.net &
          sleep 5  # Beri waktu untuk Serveo terhubung

      - name: Wait for Serveo Tunnel & Print URL
        run: |
          echo "Serveo tunnel is ready. Use this in Appium Inspector:"
          echo "Host: serveo.net"
          echo "Port: 4723"
          sleep 60
