name: Run iOS Simulator & Appium on GitHub Actions

on: [workflow_dispatch]

jobs:
  ios-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install node
          npm install -g appium
          appium -v

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 16 Pro"
          xcrun simctl list devices booted

      - name: Start Appium Server
        run: |
          appium --address 127.0.0.1 --port 4723 --allow-cors &
          sleep 10  # Tunggu Appium siap

      - name: Install & Start ngrok
        run: |
          brew install ngrok/ngrok/ngrok
          ngrok authtoken 2szG7W6hTKx1SL37QX4ScuAo5IA_3PBBVuS2tPYJhoN9EqLoU
          ngrok http 4723 > /dev/null &  # Jalankan di background
          sleep 5  # Beri waktu untuk ngrok startup

      - name: Get ngrok Public URL
        run: |
          while true; do
            NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
            if [[ "$NGROK_URL" == http* ]]; then
              echo "Ngrok is ready: $NGROK_URL"
              echo "Use this in Appium Inspector:"
              echo "Remote Server: $NGROK_URL/wd/hub"
              break
            fi
            echo "Waiting for ngrok..."
            sleep 5
          done
          sleep 60  # Tunggu tambahan 60 detik setelah ngrok siap
