name: Run iOS Simulator & Appium on GitHub Actions

on: [workflow_dispatch]

jobs:
  ios-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install node
          npm install -g appium
          appium -v

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 16 Pro"
          xcrun simctl list devices booted

      - name: Start Appium Server in Background
        run: appium --log appium.log --allow-cors &

      - name: Clone & Start Appium Inspector Web
        run: |
          git clone https://github.com/appium/appium-inspector.git
          cd appium-inspector
          npm install
          npm start &  # Gunakan `npm start` bukan `npm run dev`

      - name: Install & Run ngrok for Appium Inspector
        run: |
          brew install ngrok/ngrok/ngrok
          ngrok authtoken 2szG7W6hTKx1SL37QX4ScuAo5IA_3PBBVuS2tPYJhoN9EqLoU
          ngrok http 3000 &

      - name: Wait for ngrok & Display Public URL
        run: |
          sleep 10
          NGROK_INSPECTOR_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Appium Inspector is available at: $NGROK_INSPECTOR_URL"
          sleep 60  # Beri waktu untuk akses manual
