name: Screenshot Capture (no external module)

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - name: Take Screenshot using native PowerShell
      run: |
        Add-Type -AssemblyName System.Windows.Forms
        Add-Type -AssemblyName System.Drawing

        $screen = [System.Windows.Forms.SystemInformation]::VirtualScreen
        $bitmap = New-Object System.Drawing.Bitmap $screen.Width, $screen.Height
        $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
        $graphics.CopyFromScreen($screen.Left, $screen.Top, 0, 0, $bitmap.Size)
        $bitmap.Save("screenshot.png")

    - name: Upload Screenshot Artifact
      uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: screenshot.png
