name: Ubuntu Screenshot with Xvfb

on:
  workflow_dispatch:

jobs:
  ubuntu-screenshot:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y scrot xvfb

    - name: Start virtual display and take screenshot
      run: |
        mkdir screen
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        sleep 2  # beri waktu Xvfb start
        scrot screen/screenshot.png

    - name: Upload Screenshot
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-screenshot
        path: screen/screenshot.png
