name: Screenshot Ubuntu

on:
  workflow_dispatch:

jobs:
  ubuntu-screenshot:
    runs-on: ubuntu-latest
    steps:
    - name: Install scrot
      run: sudo apt-get update && sudo apt-get install -y scrot

    - name: Take Screenshot
      run: |
        mkdir screen
        DISPLAY=:0 scrot screen/screenshot.png

    - name: Upload Screenshot
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-screenshot
        path: screen/screenshot.png
