name: Screenshot Capture

on:
  workflow_dispatch:

jobs:
  capture-screenshot:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - name: Install PowerShellCookbook module
      run: |
        Install-Module -Name PowerShellCookbook -Force -Scope CurrentUser -AllowClobber

    - name: Capture screenshot
      run: |
        Import-Module PowerShellCookbook
        $bitmap = Capture-Screen
        $bitmap.Save("screenshot.png")

    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: screenshot.png
