name: Web Terminal (macOS)

on:
  workflow_dispatch:

jobs:
  open-terminal:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ngrok + ttyd)
        run: |
          brew install ttyd
          brew install --cask ngrok

      - name: Start web terminal via ttyd + ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          # Masukkan authtoken ngrok (pastikan sudah disimpan di Secrets)
          ngrok config add-authtoken "$NGROK_AUTH_TOKEN"

          # Jalankan ttyd di background (port default: 7681)
          nohup ttyd bash > ttyd.log 2>&1 &

          # Jalankan ngrok HTTP tunnel ke port 7681
          nohup ngrok http 7681 > ngrok.log 2>&1 &

          # Tunggu tunnel aktif
          echo "Menunggu ngrok aktif..."
          sleep 10

          echo "================ NGROK WEB TERMINAL ================"
          grep -Eo "https://[-0-9a-z]+\.ngrok.io" ngrok.log || true
          echo "===================================================="

          echo ""
          echo "✅ Buka URL di atas untuk mengakses terminal bash macOS runner"
          echo "💡 Tekan Ctrl+C untuk keluar dari sesi di dalam terminal web"
