name: Web Terminal (macOS)

on:
  workflow_dispatch:

jobs:
  open-terminal:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ngrok + ttyd + jq)
        run: |
          brew install ttyd jq
          brew install --cask ngrok

      - name: Start ttyd and ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          # Tambahkan authtoken ngrok
          ngrok config add-authtoken "$NGROK_AUTH_TOKEN"

          # Jalankan ttyd di background
          nohup ttyd bash > ttyd.log 2>&1 &

          # Jalankan ngrok (HTTP tunnel untuk ttyd)
          nohup ngrok http 7681 > ngrok.log 2>&1 &

          # Tunggu ngrok siap dan ambil URL-nya
          echo "Menunggu ngrok tunnel aktif..."
          for i in {1..20}; do
            NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
            if [[ "$NGROK_URL" == http* ]]; then
              echo "=============================================="
              echo "✅ ngrok is ready: $NGROK_URL"
              echo "💻 Web terminal dapat diakses di browser:"
              echo "$NGROK_URL"
              echo "=============================================="
              break
            fi
            echo "⏳ Waiting for ngrok to be ready ($i/20)..."
            sleep 5
          done

      - name: Keep session alive (1 hour)
        run: |
          echo "🕐 Menjaga sesi aktif selama 1 jam untuk debugging..."
          sleep 3600
